name: LongLaoshi
description: Proyecto para el curso de Ingenieria de Requisitos
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.23.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^2.2.8
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  audioplayers: ^6.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Mukta
      fonts: 
        - asset: assets/fonts/MuktaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MuktaMedium.ttf
          weight: 500
    - family: Josefin Sans
      fonts: 
        - asset: assets/fonts/JosefinSansRomanMedium.ttf
          weight: 500
